logging:
  level:
    org.springframework.beans: debug
    org.springframework.web: trace

site:
  author: SpringTestRunner
  description: What are your plans today?

todos:
  data:
    initialize: true


server:
  servlet:
    encoding:
      mapping:
        ko: UTF-8