logging:
  level:
    org.springframework.beans: debug
    org.springframework.web: trace

site:
  author: SpringTestRunner
  description: What are your plans today?

todos:
  data:
    initialize: true


server:
  servlet:
    encoding:
      mapping:
        ko: UTF-8
  error:
    include-message: always
    include-binding-errors: always

Exception:
  TodoEntityNotFoundException: 요청한 일을 찾을수 없어요.
  MethodArgumentNotValidException: 입력 값이 없거나 올바르지 않아요.